disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - force_unwrapping
  - fatal_error_message

included:
  - Sources
  - Tests

excluded:
  - .build
  - lib

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000
